PODAUTO-199: Updates for 4.17
openshift/vertical-pod-autoscaler-operator pull request #167
Opened 2024-07-04 22:08 UTC by maxcao13

Updates for 4.16

* Update deps
  * edit (update to 4.17/0.30.2) and run `hack/update-vendor.sh`
* Update code and build to match updated deps
 * Update go version to go 1.22 (go.mod, Dockerfile, images/ci/Dockerfile, Makefile) (_cannot update vet/lint/upstream-manifest because openshift/release doesnt seem to have 1.22 tag yet_)
 * Rev version from 4.16 -> 4.17: `sed -i 's/4.16/4.17/g' $(git grep -l 4.15 manifests/) images/ci/bundle.Dockerfile hack/manifest-diff-upstream.sh hack/e2e.sh Makefile`
 * Verify that Dockerfile.rhel7 & .ci-operator.yaml are up to date (they are. [Thanks, ART team](https://github.com/openshift/vertical-pod-autoscaler-operator/pull/163)!)
* Update manifests to match upstream

Had to update some struct initialization and func arguments because of a `controller-runtime` upgrade to v18.4 from v17.0 https://github.com/kubernetes-sigs/controller-runtime/pull/2783

2024-07-08 21:09 UTC, joelsmith commented
As discussed on Slack, `sed -i 's/4.16/4.17/g' $(git grep -l 4.15 manifests/)` should have been `sed -i 's/4.16/4.17/g' $(git grep -l 4.16 manifests/)`

Nice work on the controller runtime related updates!

2024-07-09 17:11 UTC, maxcao13 commented
I was looking at it, should `golint` and its scripts + ci yamls still exist? It seems to be deprecated in favour of `go vet` and Staticcheck https://github.com/golang/lint

2024-07-10 19:52 UTC, maxcao13 commented
Seems like `registry.ci.openshift.org/ocp/builder:rhel-9-golang-1.22-openshift-4.17` doesn't include `jq` and that causes `manifest-diff*.sh` scripts to fail.

2024-07-11 15:41 UTC, maxcao13 commented
Updated with new release images.

2024-07-23 01:26 UTC, joelsmith requested changes
I only see one issue with the manifest diff test. Everything else looks great! I'll watch for that to get updated then I'll add the LGTM label.

/approve

2024-07-23 01:26 UTC, joelsmith commented on hack/manifest-diff.sh
> +    /bin/bash
It looks like this was left unfinished. Should it still be `./hack/manifest-diff.sh "${@}"`?

2024-07-23 15:40 UTC, joelsmith approved these changes
/lgtm

2024-07-23 17:08 UTC, merged